#!/bin/bash
git init -qqq
git remote add origin https://github.com/bergerrc/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/bin/* ./bin/
mv compose/.vscode ./
rm -rf compose .git
git init